SCRIPTEXECUTE support
RedisAI/redisai-py pull request #68
Opened 2021-05-18 14:48 UTC by AvitalFineRedis

2021-05-19 14:14 UTC, alonre24 requested changes
Nice work! (specially for a first task in RedisAI...), please follow the comments. Note that you should indicate that `scriptrun` is deprecated by using the suitable decorator (as we do in `modelrun`).
Regarding the tests, I think that there are many redundant checks that are not specific to the redisai-py client, and that we don't need to copy those from the flow tests. On the other hand, we may want to add some tests of running scripts that are using Redis commands (we can discuss it further on slack...)

2021-05-19 14:14 UTC, alonre24 commented on test/test.py
> +    def test_scripts_execute_errors(self):
I don't think that the checks in this tests are necessary for the client, having them in RedisAI flow tests is sufficient.

2021-05-23 06:26 UTC, alonre24 commented on test/test.py
> +                    inputs=["mytensor3{1}", 3, ["mytensor1{1}", "mytensor2{1}", "mytensor3{1}]"], "alon", [1.25, 4.2]],
Please change the string input name from "alon" :)

2021-07-07 15:25 UTC, alonre24 reviewed
Nice work! Tell me if you have any questions about the comments...

2021-07-07 15:25 UTC, alonre24 commented on redisai/client.py
> +        >>> con.scriptexecute('ket', 'bar', keys=['a', 'b', 'c'], inputs=['a', 'b'], outputs=['c'])
You don't need the `keys` in this example (we want to keep in simple...)

2021-07-07 15:25 UTC, alonre24 commented on test/test.py
> +    redis.execute("SET", key, str(value))
Why using the key as `args[0]` instead of `keys[0]`? The keys param should specify the keys that are going to be accessed in Redis...

2021-07-07 15:25 UTC, alonre24 commented on test/test.py
> +        con.scriptstore("ket", "cpu", script, "bar")
Why do we use "ket" as script name all the time...?

2021-07-07 15:25 UTC, alonre24 commented on test/test.py
> +        con.scriptexecute("ket", "bar", keys=["a", "b", "c"], inputs=["a", "b"], outputs=["c"])
`keys` is redundant here...

2021-07-07 15:25 UTC, alonre24 commented on test/test.py
> +        self.assertTrue(np.allclose(values["values"], [54]))
Nice test!
You can also test that "key{1}" is deleted. Also, why sending "keys2{1} if you are not using it?

2021-07-07 15:25 UTC, alonre24 commented on redisai/client.py
> +            Any string that will be saved in RedisAI as tag for the model
tag for the script

2021-07-07 15:25 UTC, alonre24 commented on redisai/dag.py
> +
Why the changes here?

2021-07-07 15:25 UTC, alonre24 commented on test/test.py
> +    def test_deprecated_script_run(self):
`test_deprecated_scriptset_and_scriptrun`

2021-07-07 17:31 UTC, AvitalFineRedis commented on redisai/client.py
> +            Either a squence of key names that the script will access before, during and
You mean it can't be tag?

We probably should change the description of the command also:
https://oss.redislabs.com/redisai/master/commands/#aiscriptexecute

2021-07-07 17:44 UTC, AvitalFineRedis commented on redisai/dag.py
> +
I don't think it's mine :0
I saw here some of Chayim's commits

2021-07-07 17:45 UTC, AvitalFineRedis commented on redisai/pipeline.py
> +from typing import AnyStr, Union, Sequence
This definitely belongs to Chayim!
He loves his imports sorted...

2021-07-11 10:32 UTC, alonre24 commented on redisai/client.py
> +            Either a squence of key names that the script will access before, during and
Well, actually it can be a tag, but we shouldn't put it the description... I will update it in the command description as well

2021-07-11 10:35 UTC, alonre24 commented on redisai/pipeline.py
> +from typing import AnyStr, Union, Sequence
Always blame Chayim! :)
Anyway, let's be consistent with what master has currently... (and Chayim is welcome to sort his imports in a designated PR)

2021-07-11 10:35 UTC, alonre24 commented on redisai/dag.py
> +
Same as above :)

2021-07-18 07:36 UTC, AvitalFineRedis commented on redisai/dag.py
> +
I see here some functions that use `builder`. The `DagTestCase` does not pass without this import

2021-07-18 08:01 UTC, alonre24 reviewed
Nice! Almost ready, just some few small comments

2021-07-18 10:37 UTC, AvitalFineRedis commented on redisai/pipeline.py
> +import redis
`PipelineTest` does not pass without it

2021-07-18 11:10 UTC, alonre24 approved these changes
Nice work!

2021-07-18 11:14 UTC, merged